theme = "onedark"  # also notable: base16_transparent, onedark, snazzy, dracula, zed_onedark

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true  # fixes https://github.com/helix-editor/helix/issues/1271
bufferline = "never"
rulers = [80]
auto-save = true
shell = ["bash", "-c"]

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "version-control", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

# # Escape the madness! No more fighting with the cursor! Or with multiple cursors!
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
X = "extend_line_above"

[keys.normal.Z]
# Z = ":write-buffer-close"
# Q = ":buffer-close!"
Z = ":write-quit"
Q = ":quit-all"

[keys.normal."+"]
m = ":run-shell-command make"